//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemperatureControlService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Zones {
            get {
                return ((int)(this["Zones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int Interval {
            get {
                return ((int)(this["Interval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{'id':'1','setpointFile':'c:/temp/sp1','setpoint':'60','feedbackFile':'','feedback':'0','outputGroup':'a','outputId':'1','currentState':'off','hysterisis':'1','calibration':'-8'},{'id':'2','setpointFile':'c:/temp/sp2','setpoint':'60','feedbackFile':'','feedback':'0','outputGroup':'a','outputId':'2','currentState':'off','hysterisis':'1','calibration':'-8'},{'id':'3','setpointFile':'c:/temp/sp3','setpoint':'60','feedbackFile':'','feedback':'0','outputGroup':'a','outputId':'3','currentState':'off','hysterisis':'1','calibration':'-8'}]")]
        public string TempZones {
            get {
                return ((string)(this["TempZones"]));
            }
        }
    }
}
