//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempControlLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int zones {
            get {
                return ((int)(this["zones"]));
            }
            set {
                this["zones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\'id\':\'1\',\'setpointFile\':\'c:/temp/sp1\',\'setpoint\':\'60\',\'feedbackFile\':\'c:/temp/f" +
            "b1\',\'feedback\':\'0\',\'outputGroup\':\'a\',\'outputId\':\'1\',\'currentState\':\'off\',\'hyster" +
            "isis\':\'1\',\'calibration\':\'-4\',\'ip\':\'192.168.1.7\',\'port\':\'49153\'}]")]
        public string TempZones {
            get {
                return ((string)(this["TempZones"]));
            }
            set {
                this["TempZones"] = value;
            }
        }
    }
}
